set_property PACKAGE_PIN P16 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
create_clock -period 11.111 -name sys_clk [get_ports clk]
set_property PACKAGE_PIN U4 [get_ports rst]
set_property IOSTANDARD SSTL15 [get_ports rst]
set_property PACKAGE_PIN U6 [get_ports load]
set_property IOSTANDARD SSTL15 [get_ports load]
set_property PACKAGE_PIN P6 [get_ports shift]
set_property IOSTANDARD SSTL15 [get_ports shift]
set_property PACKAGE_PIN U5 [get_ports serial_in]
set_property IOSTANDARD SSTL15 [get_ports serial_in]
set_property PACKAGE_PIN T5 [get_ports {mode[0]}]
set_property IOSTANDARD SSTL15 [get_ports {mode[0]}]
set_property PACKAGE_PIN R5 [get_ports {mode[1]}]
set_property IOSTANDARD SSTL15 [get_ports {mode[1]}]
set_property PACKAGE_PIN R8 [get_ports {parallel_in[0]}]
set_property IOSTANDARD SSTL15 [get_ports {parallel_in[0]}]
set_property PACKAGE_PIN P8 [get_ports {parallel_in[1]}]
set_property IOSTANDARD SSTL15 [get_ports {parallel_in[1]}]
set_property PACKAGE_PIN R7 [get_ports {parallel_in[2]}]
set_property IOSTANDARD SSTL15 [get_ports {parallel_in[2]}]
set_property PACKAGE_PIN R6 [get_ports {parallel_in[3]}]
set_property IOSTANDARD SSTL15 [get_ports {parallel_in[3]}]
set_property PACKAGE_PIN M26 [get_ports {parallel_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {parallel_out[0]}]
set_property PACKAGE_PIN T24 [get_ports {parallel_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {parallel_out[1]}]
set_property PACKAGE_PIN T25 [get_ports {parallel_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {parallel_out[2]}]
set_property PACKAGE_PIN R26 [get_ports {parallel_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {parallel_out[3]}]
set_property PACKAGE_PIN P26 [get_ports serial_out]
set_property IOSTANDARD LVCMOS33 [get_ports serial_out]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]