set_property PACKAGE_PIN R8 [get_ports {A[0]}]
set_property IOSTANDARD SSTL15 [get_ports {A[0]}]
set_property PACKAGE_PIN P8 [get_ports {A[1]}]
set_property IOSTANDARD SSTL15 [get_ports {A[1]}]
set_property PACKAGE_PIN R7 [get_ports {A[2]}]
set_property IOSTANDARD SSTL15 [get_ports {A[2]}]
set_property PACKAGE_PIN R6 [get_ports {A[3]}]
set_property IOSTANDARD SSTL15 [get_ports {A[3]}]

set_property PACKAGE_PIN P6 [get_ports {B[0]}]
set_property IOSTANDARD SSTL15 [get_ports {B[0]}]
set_property PACKAGE_PIN U5 [get_ports {B[1]}]
set_property IOSTANDARD SSTL15 [get_ports {B[1]}]
set_property PACKAGE_PIN T5 [get_ports {B[2]}]
set_property IOSTANDARD SSTL15 [get_ports {B[2]}]
set_property PACKAGE_PIN R5 [get_ports {B[3]}]
set_property IOSTANDARD SSTL15 [get_ports {B[3]}]

set_property PACKAGE_PIN N22 [get_ports {ALU_selection[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_selection[0]}]
set_property PACKAGE_PIN P20 [get_ports {ALU_selection[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_selection[1]}]
set_property PACKAGE_PIN N21 [get_ports {ALU_selection[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_selection[2]}]
set_property PACKAGE_PIN U6 [get_ports {ALU_selection[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ALU_selection[3]}]

set_property PACKAGE_PIN M26 [get_ports {ALU_Output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Output[0]}]
set_property PACKAGE_PIN T24 [get_ports {ALU_Output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Output[1]}]
set_property PACKAGE_PIN T25 [get_ports {ALU_Output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Output[2]}]
set_property PACKAGE_PIN R26 [get_ports {ALU_Output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Output[3]}]

set_property PACKAGE_PIN P26 [get_ports Cout]
set_property IOSTANDARD LVCMOS33 [get_ports Cout]